services:
  db:
    image: postgres:16-alpine
    container_name: py-auth-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: pyauth
      POSTGRES_PASSWORD: pyauth
      POSTGRES_DB: pyauth
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
