name: CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      # If the cache is missing (first run or invalidated), the
      # cache step exposes NO key, producing an empty output → downstream jobs fail with:
      # "Error: Input required and not supplied: key".
      # So we specifically create a key as send it to putput in this job
      poetry_cache_key: ${{ steps.cache-key.outputs.key }}

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Compute deterministic cache key
        id: cache-key
        # We compute the key once here and reuse it across all jobs.
        # It's based on OS + hash of poetry.lock → stable and reproducible.
        run: echo "key=${{ runner.os }}-poetry-${{ hashFiles('backend/poetry.lock') }}" >> "$GITHUB_OUTPUT"

      - name: Cache Poetry + virtualenv
        id: poetry-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            backend/.venv
          key: ${{ steps.cache-key.outputs.key }}

      - name: Install dependencies
        run: poetry install --no-interaction --no-root


  lint:
    runs-on: ubuntu-latest
    needs: setup
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Restore Poetry + venv cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            backend/.venv
          key: ${{ needs.setup.outputs.poetry_cache_key }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      # Required when running locally with `act` (because act does not support cache restore)
      - name: Install deps (needed only for act)
        run: poetry install --no-interaction --no-root

      - name: Ruff lint
        run: poetry run ruff check --output-format=github .


  format:
    runs-on: ubuntu-latest
    needs: setup
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Restore Poetry + venv cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            backend/.venv
          key: ${{ needs.setup.outputs.poetry_cache_key }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      # Required when running locally with `act`
      - name: Install deps (needed only for act)
        run: poetry install --no-interaction --no-root

      - name: Check formatting
        run: poetry run ruff format --check .